export const modalStyles = {
  overlay: {
    position: "fixed",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0, 0, 0, 0.6)",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 1000,
  },
  content: {
    background: "#2d3748",
    color: "#f3f4f6",
    padding: "2rem",
    borderRadius: "0.5rem",
    maxWidth: "600px",
    width: "90%",
  },
  radiobutton: {
    display: "flex",
    gap: "1rem",
    marginBottom: "1rem",
  },
  container: {
    display: "flex",
    gap: "2rem",
  },
  register: {
    flex: 1,
  },
  preview: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: "6px",
  },
  inputs: {
    display: "flex",
    flexDirection: "column",
    gap: "0.75rem",
    marginTop: "0.75rem",
  },
};

export const buttonStyle = {
  confirm: {
    backgroundColor: "#48bb78",
    color: "white",
    border: "none",
    padding: "0.75rem 1.5rem",
    borderRadius: "0.375rem",
    cursor: "pointer",
    fontSize: "0.875rem",
    fontWeight: "500",
  },
  cancel: {
    backgroundColor: "#718096",
    color: "white",
    border: "none",
    padding: "0.75rem 1.5rem",
    borderRadius: "0.375rem",
    cursor: "pointer",
    fontSize: "0.875rem",
    fontWeight: "500",
  },
  delete: {
    backgroundColor: "#e53e3e",
    color: "white",
    border: "none",
    padding: "0.5rem 1rem",
    borderRadius: "0.25rem",
    cursor: "pointer",
    fontSize: "0.75rem",
  },
  obsButton: {
    background: "#4a5568",
    color: "#f3f4f6",
    border: "none",
    borderRadius: "0.25rem",
    padding: "0.5rem",
    cursor: "pointer",
    outline: "none",
  },
  obsButtonActive: {
    background: "#2d3748",
    color: "#cbd5e0",
    border: "none",
    borderRadius: "0.25rem",
    padding: "0.5rem",
    cursor: "pointer",
    outline: "none",
  },
};